/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.newspaper.gui;

import com.newspaper.db.DBconnection;
import com.newspaper.deliverydocket.DeliveryDocket;
import com.newspaper.deliverydocket.DeliveryDocketDB;
import com.newspaper.deliverydocket.DeliveryDocketExceptionHandler;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.time.LocalDate;

/**
 *
 * @author Ray
 */
public class DeliveryDocketMainGUI extends javax.swing.JFrame {

    /**
     * Creates new form GuiMainMenu
     */
    public DeliveryDocketMainGUI() {
        initComponents();
        DBconnection.init_db();
        tfDateOnCreate.setText(LocalDate.now().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnCreateDocketMenu = new javax.swing.JButton();
        btnEditDocketMenu = new javax.swing.JButton();
        btnDeleteDocketMenu = new javax.swing.JButton();
        btnCustomerDeliveriesMenu = new javax.swing.JButton();
        btnPublicationDeliveries = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CentrePanel = new javax.swing.JPanel();
        CreateDeliveryDocket = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfDeliveryPersonIDoncreate = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        tfDateOnCreate = new javax.swing.JTextField();
        btnSubmitDeliveryPersonIdOnCreate = new javax.swing.JButton();
        btnSubmitDateOnCreate = new javax.swing.JButton();
        tfWarningCREATE = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfDeliveryDocketAreaCREATE = new javax.swing.JTextArea();
        jScrollBar1 = new javax.swing.JScrollBar();
        DisplayAll = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jButton25 = new javax.swing.JButton();
        jTextField22 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jTextField23 = new javax.swing.JTextField();
        DeleteDeliveryDocket = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jButton29 = new javax.swing.JButton();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jTextField41 = new javax.swing.JTextField();
        jButton33 = new javax.swing.JButton();
        jTextField44 = new javax.swing.JTextField();
        SeeAllCustomerDeliveries = new javax.swing.JPanel();
        DisplayOne3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jButton24 = new javax.swing.JButton();
        jTextField17 = new javax.swing.JTextField();
        SeeAllPublicationDeliveries = new javax.swing.JPanel();
        DisplayOne1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jButton22 = new javax.swing.JButton();
        jTextField30 = new javax.swing.JTextField();


        btnSubmitDeliveryPersonIdOnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitDeliveryPersonIdOnCreate(evt);
            }
        });

        btnSubmitDateOnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitDateOnCreate(evt);
            }
        });


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(19, 28, 33));

        jPanel3.setBackground(new java.awt.Color(19, 28, 33));

        btnCreateDocketMenu.setBackground(new java.awt.Color(19, 28, 33));
        btnCreateDocketMenu.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnCreateDocketMenu.setForeground(new java.awt.Color(49, 117, 108));
        btnCreateDocketMenu.setText("Create Docket");
        btnCreateDocketMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCreateDocketMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnEditDocketMenu.setBackground(new java.awt.Color(19, 28, 33));
        btnEditDocketMenu.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnEditDocketMenu.setForeground(new java.awt.Color(49, 117, 108));
        btnEditDocketMenu.setText("Edit Docket");
        btnEditDocketMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditDocketMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnDeleteDocketMenu.setBackground(new java.awt.Color(19, 28, 33));
        btnDeleteDocketMenu.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnDeleteDocketMenu.setForeground(new java.awt.Color(49, 117, 108));
        btnDeleteDocketMenu.setText("Delete");
        btnDeleteDocketMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDeleteDocketMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnCustomerDeliveriesMenu.setBackground(new java.awt.Color(19, 28, 33));
        btnCustomerDeliveriesMenu.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnCustomerDeliveriesMenu.setForeground(new java.awt.Color(49, 117, 108));
        btnCustomerDeliveriesMenu.setText("Customer Deliveries");
        btnCustomerDeliveriesMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCustomerDeliveriesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnPublicationDeliveries.setBackground(new java.awt.Color(19, 28, 33));
        btnPublicationDeliveries.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnPublicationDeliveries.setForeground(new java.awt.Color(49, 117, 108));
        btnPublicationDeliveries.setText("Publication Deliveries");
        btnPublicationDeliveries.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPublicationDeliveries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(19, 28, 33));
        jButton7.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(6, 187, 163));
        jButton7.setText("Main Menu");
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(19, 28, 33));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1295, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnEditDocketMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCreateDocketMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnDeleteDocketMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCustomerDeliveriesMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnPublicationDeliveries, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnCreateDocketMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditDocketMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDeleteDocketMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCustomerDeliveriesMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(btnPublicationDeliveries, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(19, 28, 33));

        jLabel1.setIcon(new ImageIcon(getClass().getResource("../images/NewspaperLogoDarkGreenSmall.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Niagara Engraved", 0, 140)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(49, 117, 108));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Delivery Docket Menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CentrePanel.setLayout(new java.awt.CardLayout());

        CreateDeliveryDocket.setBackground(new java.awt.Color(19, 28, 33));

        jPanel4.setBackground(new java.awt.Color(19, 28, 33));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(6, 187, 163));
        jLabel3.setText("Enter Delivery Person ID");

        tfDeliveryPersonIDoncreate.setBackground(new java.awt.Color(0, 102, 102));

        jTextField2.setBackground(new java.awt.Color(19, 28, 39));
        jTextField2.setForeground(new java.awt.Color(18, 30, 49));
        jTextField2.setBorder(null);
        jTextField2.setDisabledTextColor(new java.awt.Color(19, 28, 33));
        jTextField2.setFocusable(false);
        jTextField2.setSelectedTextColor(new java.awt.Color(19, 28, 33));

        jLabel30.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(6, 187, 163));
        jLabel30.setText("Enter Date of Delivery Docket");

        tfDateOnCreate.setBackground(new java.awt.Color(0, 102, 102));

        btnSubmitDeliveryPersonIdOnCreate.setBackground(new java.awt.Color(49, 117, 108));
        btnSubmitDeliveryPersonIdOnCreate.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnSubmitDeliveryPersonIdOnCreate.setForeground(new java.awt.Color(0, 0, 0));
        btnSubmitDeliveryPersonIdOnCreate.setText("Submit");

        btnSubmitDateOnCreate.setBackground(new java.awt.Color(49, 117, 108));
        btnSubmitDateOnCreate.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnSubmitDateOnCreate.setForeground(new java.awt.Color(0, 0, 0));
        btnSubmitDateOnCreate.setText("Submit");

        tfWarningCREATE.setBackground(new java.awt.Color(19, 28, 33));
        tfWarningCREATE.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        tfWarningCREATE.setForeground(new java.awt.Color(255, 0, 0));
        tfWarningCREATE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfWarningCREATE.setText("Warning Messages");
        tfWarningCREATE.setBorder(null);

        tfDeliveryDocketAreaCREATE.setEditable(false);
        tfDeliveryDocketAreaCREATE.setBackground(new java.awt.Color(19, 28, 33));
        tfDeliveryDocketAreaCREATE.setColumns(20);
        tfDeliveryDocketAreaCREATE.setForeground(new java.awt.Color(49, 117, 108));
        tfDeliveryDocketAreaCREATE.setRows(5);
        tfDeliveryDocketAreaCREATE.setFont(new java.awt.Font("sansserif", 0, 24));
        tfDeliveryDocketAreaCREATE.setText("Text Here");
        jScrollPane2.setViewportView(tfDeliveryDocketAreaCREATE);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(tfDeliveryPersonIDoncreate, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tfDateOnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(39, 39, 39)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addComponent(btnSubmitDateOnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(251, 251, 251)
                                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(btnSubmitDeliveryPersonIdOnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addComponent(tfWarningCREATE, javax.swing.GroupLayout.PREFERRED_SIZE, 1232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfDeliveryPersonIDoncreate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSubmitDeliveryPersonIdOnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(tfDateOnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnSubmitDateOnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfWarningCREATE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE))
                                .addContainerGap())
        );

        javax.swing.GroupLayout CreateDeliveryDocketLayout = new javax.swing.GroupLayout(CreateDeliveryDocket);
        CreateDeliveryDocket.setLayout(CreateDeliveryDocketLayout);
        CreateDeliveryDocketLayout.setHorizontalGroup(
                CreateDeliveryDocketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1312, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        CreateDeliveryDocketLayout.setVerticalGroup(
                CreateDeliveryDocketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CreateDeliveryDocketLayout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        CentrePanel.add(CreateDeliveryDocket, "card3");

        DisplayAll.setBackground(new java.awt.Color(19, 28, 33));

        jScrollPane1.setBackground(new java.awt.Color(19, 28, 33));

        jTable1.setBackground(new java.awt.Color(19, 28, 33));
        jTable1.setForeground(new java.awt.Color(49, 117, 108));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13"
                }
        ));
        jTable1.setGridColor(new java.awt.Color(49, 117, 108));
        jScrollPane1.setViewportView(jTable1);

        jLabel32.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(6, 187, 163));
        jLabel32.setText("Enter Delivery Person ID");

        jLabel33.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(6, 187, 163));
        jLabel33.setText("Enter Date of Delivery Docket");

        jLabel34.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(6, 187, 163));
        jLabel34.setText("Have ALL items been Delivered?");

        jLabel35.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(6, 187, 163));
        jLabel35.setText("Enter ID's of any non Delivered Items");

        jButton25.setBackground(new java.awt.Color(49, 117, 108));
        jButton25.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton25.setForeground(new java.awt.Color(0, 0, 0));
        jButton25.setText("Submit");

        jTextField22.setBackground(new java.awt.Color(0, 102, 102));

        jTextField24.setBackground(new java.awt.Color(0, 102, 102));

        jTextField25.setBackground(new java.awt.Color(0, 102, 102));

        jButton26.setBackground(new java.awt.Color(49, 117, 108));
        jButton26.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton26.setForeground(new java.awt.Color(0, 0, 0));
        jButton26.setText("Submit");

        jButton27.setBackground(new java.awt.Color(49, 117, 108));
        jButton27.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton27.setForeground(new java.awt.Color(0, 0, 0));
        jButton27.setText("YES");

        jButton28.setBackground(new java.awt.Color(49, 117, 108));
        jButton28.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton28.setForeground(new java.awt.Color(0, 0, 0));
        jButton28.setText("Submit");

        jTextField23.setBackground(new java.awt.Color(19, 28, 33));
        jTextField23.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTextField23.setForeground(new java.awt.Color(255, 0, 0));
        jTextField23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField23.setText("Warning Text");
        jTextField23.setBorder(null);

        javax.swing.GroupLayout DisplayAllLayout = new javax.swing.GroupLayout(DisplayAll);
        DisplayAll.setLayout(DisplayAllLayout);
        DisplayAllLayout.setHorizontalGroup(
                DisplayAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DisplayAllLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(DisplayAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addGroup(DisplayAllLayout.createSequentialGroup()
                                                .addGroup(DisplayAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                                                        .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(34, 34, 34)
                                                .addGroup(DisplayAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(56, 56, 56)
                                                .addGroup(DisplayAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 598, Short.MAX_VALUE))
                                        .addComponent(jTextField23))
                                .addContainerGap())
        );
        DisplayAllLayout.setVerticalGroup(
                DisplayAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DisplayAllLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(DisplayAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(DisplayAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(DisplayAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(DisplayAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
        );

        CentrePanel.add(DisplayAll, "card2");

        DeleteDeliveryDocket.setBackground(new java.awt.Color(19, 28, 33));

        jLabel36.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(6, 187, 163));
        jLabel36.setText("Enter Delivery Person ID");

        jLabel37.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(6, 187, 163));
        jLabel37.setText("Enter Date of Delivery Docket");

        jLabel38.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(6, 187, 163));
        jLabel38.setText("Are You SURE you want to DELETE this Docket");

        jButton29.setBackground(new java.awt.Color(49, 117, 108));
        jButton29.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton29.setForeground(new java.awt.Color(0, 0, 0));
        jButton29.setText("Submit");

        jTextField26.setBackground(new java.awt.Color(0, 102, 102));

        jTextField27.setBackground(new java.awt.Color(0, 102, 102));

        jButton30.setBackground(new java.awt.Color(49, 117, 108));
        jButton30.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton30.setForeground(new java.awt.Color(0, 0, 0));
        jButton30.setText("Submit");

        jButton31.setBackground(new java.awt.Color(49, 117, 108));
        jButton31.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton31.setForeground(new java.awt.Color(0, 0, 0));
        jButton31.setText("YES");

        jTextField41.setBackground(new java.awt.Color(19, 28, 33));
        jTextField41.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTextField41.setForeground(new java.awt.Color(255, 0, 0));
        jTextField41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField41.setText("Warning Text ****");
        jTextField41.setBorder(null);
        jTextField41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField41ActionPerformed(evt);
            }
        });

        jButton33.setBackground(new java.awt.Color(49, 117, 108));
        jButton33.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton33.setForeground(new java.awt.Color(0, 0, 0));
        jButton33.setText("NO");

        jTextField44.setBackground(new java.awt.Color(19, 28, 33));
        jTextField44.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jTextField44.setForeground(new java.awt.Color(49, 117, 108));
        jTextField44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField44.setText("**** TEXT AREA FOR DELIVERY DOCKET ****");

        javax.swing.GroupLayout DeleteDeliveryDocketLayout = new javax.swing.GroupLayout(DeleteDeliveryDocket);
        DeleteDeliveryDocket.setLayout(DeleteDeliveryDocketLayout);
        DeleteDeliveryDocketLayout.setHorizontalGroup(
                DeleteDeliveryDocketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeleteDeliveryDocketLayout.createSequentialGroup()
                                .addGroup(DeleteDeliveryDocketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField44)
                                        .addGroup(DeleteDeliveryDocketLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(DeleteDeliveryDocketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(DeleteDeliveryDocketLayout.createSequentialGroup()
                                                                .addGroup(DeleteDeliveryDocketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(DeleteDeliveryDocketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(56, 56, 56)
                                                                .addGroup(DeleteDeliveryDocketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(DeleteDeliveryDocketLayout.createSequentialGroup()
                                                                                .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(0, 479, Short.MAX_VALUE))
                                                        .addComponent(jTextField41))))
                                .addContainerGap())
        );
        DeleteDeliveryDocketLayout.setVerticalGroup(
                DeleteDeliveryDocketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DeleteDeliveryDocketLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(DeleteDeliveryDocketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(DeleteDeliveryDocketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(DeleteDeliveryDocketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jTextField41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField44, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
        );

        CentrePanel.add(DeleteDeliveryDocket, "card8");

        DisplayOne3.setBackground(new java.awt.Color(19, 28, 33));

        jScrollPane5.setBackground(new java.awt.Color(19, 28, 33));

        jTable5.setBackground(new java.awt.Color(19, 28, 33));
        jTable5.setForeground(new java.awt.Color(49, 117, 108));
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13"
                }
        ));
        jTable5.setGridColor(new java.awt.Color(49, 117, 108));
        jScrollPane5.setViewportView(jTable5);

        jPanel8.setBackground(new java.awt.Color(19, 28, 33));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(6, 187, 163));
        jLabel4.setText("Please enter the id of the Customer that you would like to display");

        jTextField16.setBackground(new java.awt.Color(0, 102, 102));

        jButton24.setBackground(new java.awt.Color(49, 117, 108));
        jButton24.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton24.setForeground(new java.awt.Color(0, 0, 0));
        jButton24.setText("Submit");

        jTextField17.setBackground(new java.awt.Color(19, 28, 39));
        jTextField17.setForeground(new java.awt.Color(18, 30, 49));
        jTextField17.setBorder(null);
        jTextField17.setDisabledTextColor(new java.awt.Color(19, 28, 33));
        jTextField17.setFocusable(false);
        jTextField17.setSelectedTextColor(new java.awt.Color(19, 28, 33));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 340, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addComponent(jTextField16, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                                .addGap(2, 2, 2))
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButton24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout DisplayOne3Layout = new javax.swing.GroupLayout(DisplayOne3);
        DisplayOne3.setLayout(DisplayOne3Layout);
        DisplayOne3Layout.setHorizontalGroup(
                DisplayOne3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane5)
        );
        DisplayOne3Layout.setVerticalGroup(
                DisplayOne3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DisplayOne3Layout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout SeeAllCustomerDeliveriesLayout = new javax.swing.GroupLayout(SeeAllCustomerDeliveries);
        SeeAllCustomerDeliveries.setLayout(SeeAllCustomerDeliveriesLayout);
        SeeAllCustomerDeliveriesLayout.setHorizontalGroup(
                SeeAllCustomerDeliveriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1318, Short.MAX_VALUE)
                        .addGroup(SeeAllCustomerDeliveriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(SeeAllCustomerDeliveriesLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(DisplayOne3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
        SeeAllCustomerDeliveriesLayout.setVerticalGroup(
                SeeAllCustomerDeliveriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 776, Short.MAX_VALUE)
                        .addGroup(SeeAllCustomerDeliveriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(SeeAllCustomerDeliveriesLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(DisplayOne3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );

        CentrePanel.add(SeeAllCustomerDeliveries, "card6");

        SeeAllPublicationDeliveries.setBackground(new java.awt.Color(19, 28, 33));

        DisplayOne1.setBackground(new java.awt.Color(19, 28, 33));

        jScrollPane3.setBackground(new java.awt.Color(19, 28, 33));

        jTable3.setBackground(new java.awt.Color(19, 28, 33));
        jTable3.setForeground(new java.awt.Color(49, 117, 108));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13"
                }
        ));
        jTable3.setGridColor(new java.awt.Color(49, 117, 108));
        jScrollPane3.setViewportView(jTable3);

        jPanel5.setBackground(new java.awt.Color(19, 28, 33));

        jLabel53.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(6, 187, 163));
        jLabel53.setText("Please enter the id of the Publication that you would like to Display");

        jTextField29.setBackground(new java.awt.Color(0, 102, 102));

        jButton22.setBackground(new java.awt.Color(49, 117, 108));
        jButton22.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton22.setForeground(new java.awt.Color(0, 0, 0));
        jButton22.setText("Submit");

        jTextField30.setBackground(new java.awt.Color(19, 28, 39));
        jTextField30.setForeground(new java.awt.Color(18, 30, 49));
        jTextField30.setBorder(null);
        jTextField30.setDisabledTextColor(new java.awt.Color(19, 28, 33));
        jTextField30.setFocusable(false);
        jTextField30.setSelectedTextColor(new java.awt.Color(19, 28, 33));
        jTextField30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField30ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 347, Short.MAX_VALUE))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jTextField29, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                                .addGap(2, 2, 2))
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jButton22)
                                                .addComponent(jTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DisplayOne1Layout = new javax.swing.GroupLayout(DisplayOne1);
        DisplayOne1.setLayout(DisplayOne1Layout);
        DisplayOne1Layout.setHorizontalGroup(
                DisplayOne1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DisplayOne1Layout.createSequentialGroup()
                                .addGroup(DisplayOne1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane3))
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        DisplayOne1Layout.setVerticalGroup(
                DisplayOne1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DisplayOne1Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SeeAllPublicationDeliveriesLayout = new javax.swing.GroupLayout(SeeAllPublicationDeliveries);
        SeeAllPublicationDeliveries.setLayout(SeeAllPublicationDeliveriesLayout);
        SeeAllPublicationDeliveriesLayout.setHorizontalGroup(
                SeeAllPublicationDeliveriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1335, Short.MAX_VALUE)
                        .addGroup(SeeAllPublicationDeliveriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(SeeAllPublicationDeliveriesLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(DisplayOne1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
        SeeAllPublicationDeliveriesLayout.setVerticalGroup(
                SeeAllPublicationDeliveriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 816, Short.MAX_VALUE)
                        .addGroup(SeeAllPublicationDeliveriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(SeeAllPublicationDeliveriesLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(DisplayOne1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );

        CentrePanel.add(SeeAllPublicationDeliveries, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(CentrePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1318, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CentrePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(ActionEvent evt) {
        if (evt.getSource() == btnCreateDocketMenu) {

            CreateDeliveryDocket.setVisible(true);
            DisplayAll.setVisible(false);
            DeleteDeliveryDocket.setVisible(false);
            SeeAllCustomerDeliveries.setVisible(false);
            SeeAllPublicationDeliveries.setVisible(false);

            // set auto date
            tfDateOnCreate.setText(LocalDate.now().toString());

        }
    }

    private void jButton3ActionPerformed(ActionEvent evt) {
        if (evt.getSource() == btnEditDocketMenu) {

            CreateDeliveryDocket.setVisible(false);
            DisplayAll.setVisible(true);
            DeleteDeliveryDocket.setVisible(false);
            SeeAllCustomerDeliveries.setVisible(false);
            SeeAllPublicationDeliveries.setVisible(false);

        }
    }

    private void jButton4ActionPerformed(ActionEvent evt) {
        if (evt.getSource() == btnDeleteDocketMenu) {

            CreateDeliveryDocket.setVisible(false);
            DisplayAll.setVisible(false);
            DeleteDeliveryDocket.setVisible(true);
            SeeAllCustomerDeliveries.setVisible(false);
            SeeAllPublicationDeliveries.setVisible(false);

        }
    }

    private void jButton5ActionPerformed(ActionEvent evt) {
        if (evt.getSource() == btnCustomerDeliveriesMenu) {

            CreateDeliveryDocket.setVisible(false);
            DisplayAll.setVisible(false);
            DeleteDeliveryDocket.setVisible(false);
            SeeAllCustomerDeliveries.setVisible(true);
            SeeAllPublicationDeliveries.setVisible(false);

        }
    }

    private void jButton6ActionPerformed(ActionEvent evt) {
        if (evt.getSource() == btnPublicationDeliveries) {

            CreateDeliveryDocket.setVisible(false);
            DisplayAll.setVisible(false);
            DeleteDeliveryDocket.setVisible(false);
            SeeAllCustomerDeliveries.setVisible(false);
            SeeAllPublicationDeliveries.setVisible(true);

        }
    }

    private void jButton7ActionPerformed(ActionEvent evt) {
        MainAdminScreenGUI mainAdminScreenGUI = new MainAdminScreenGUI();
        dispose();
        mainAdminScreenGUI.setVisible(true);
    }

    // error check on submitting
    private void submitDeliveryPersonIdOnCreate(ActionEvent evt) {
        checkDeliveryPersonIdObCreate();
    }

    public int checkDeliveryPersonIdObCreate() {
        String deliveryPersonId = tfDeliveryPersonIDoncreate.getText();
        int id = 0;
        try {
            id = handler.validateDeliveryPersonId(deliveryPersonId);
            tfWarningCREATE.setText("All ok");
        }
        catch (DeliveryDocketExceptionHandler e) {
            tfWarningCREATE.setText(e.getMessage());
        }
        return id;
    }

    // error check on submitting
    private void submitDateOnCreate(ActionEvent evt) {
        String date = tfDateOnCreate.getText();

        try {
            // try validating date
            deliveryDocket.validateDate(date);

            // if date is correct, create and display delivery docket
            deliveryDocketDB.generateDeliveriesIfNeeded(date);

            int deliveryPersonId = checkDeliveryPersonIdObCreate();


            // 6. Create delivery docket file and show on console
            try {

                DeliveryDocket docket = deliveryDocketDB.createDeliveryDocketFor(deliveryPersonId, date);
                tfDeliveryDocketAreaCREATE.setText(docket.toString());
                deliveryDocketDB.createDeliveryDocketFile(docket);
            } catch (DeliveryDocketExceptionHandler e) {
                System.out.println(e.getMessage());
            }

        } catch (DeliveryDocketExceptionHandler e) {
            tfWarningCREATE.setText(e.getMessage());
        }
        catch (Exception e) {
            tfWarningCREATE.setText("Date format incorrect");
        }
    }


    private void jTextField30ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextField41ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryDocketMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryDocketMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryDocketMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryDocketMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryDocketMainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel CentrePanel;
    private javax.swing.JPanel CreateDeliveryDocket;
    private javax.swing.JPanel DeleteDeliveryDocket;
    private javax.swing.JPanel DisplayAll;
    private javax.swing.JPanel DisplayOne1;
    private javax.swing.JPanel DisplayOne3;
    private javax.swing.JPanel SeeAllCustomerDeliveries;
    private javax.swing.JPanel SeeAllPublicationDeliveries;
    private javax.swing.JButton btnCreateDocketMenu;
    private javax.swing.JButton btnSubmitDeliveryPersonIdOnCreate;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton btnSubmitDateOnCreate;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton btnEditDocketMenu;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton btnDeleteDocketMenu;
    private javax.swing.JButton btnCustomerDeliveriesMenu;
    private javax.swing.JButton btnPublicationDeliveries;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextArea tfDeliveryDocketAreaCREATE;
    private javax.swing.JTextField tfDeliveryPersonIDoncreate;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField tfDateOnCreate;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField tfWarningCREATE;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField44;
    // End of variables declaration


    DeliveryDocketHandler handler = new DeliveryDocketHandler();
    DeliveryDocket deliveryDocket = new DeliveryDocket();
    DeliveryDocketDB deliveryDocketDB = new DeliveryDocketDB();
}
